# Markdownlint configuration for Hugo blog
# Based on: https://github.com/DavidAnson/markdownlint

# Line length
MD013:
  line_length: 120
  code_blocks: false
  tables: false

# First line should be a top level heading
MD041: false

# Multiple consecutive blank lines
MD012:
  maximum: 2

# Inline HTML
MD033: false

# Emphasis used instead of a heading
MD036: false

# Lists should be surrounded by blank lines
MD032: false

# Fenced code blocks should have a language specified
MD040: false
