baseURL = 'https://jmalicki.github.io/'
languageCode = 'en-us'
title = 'My Blog'
theme = 'stack'
copyright = 'Joseph Malicki'

[params]
  mainSections = ['post']
  featuredImageField = 'image'
  rssFullContent = true
  
  [params.sidebar]
    emoji = '📝'
    subtitle = 'A blog about technology and development'
    avatar = { enabled = true, local = true, src = 'img/avatar.png' }
  
  [params.article]
    math = false
    toc = true
    readingTime = true
    license = { enabled = true, default = 'Licensed under CC BY-NC-SA 4.0' }
  
  [params.comments]
    enabled = false
  
  [params.widgets]
    homepage = [
      { type = 'search' },
      { type = 'archives', params = { limit = 5 } },
      { type = 'categories', params = { limit = 10 } },
      { type = 'tag-cloud', params = { limit = 10 } }
    ]
    page = [
      { type = 'toc' }
    ]
  
  [params.colorScheme]
    toggle = true
    default = 'auto'
  
  [params.imageProcessing]
    cover = { enabled = true }
    content = { enabled = true }

[menu]
  [[menu.main]]
    identifier = 'home'
    name = 'Home'
    url = '/'
    weight = 1
  
  [[menu.main]]
    identifier = 'archives'
    name = 'Archives'
    url = '/archives/'
    weight = 2
  
  [[menu.social]]
    identifier = 'github'
    name = 'GitHub'
    url = 'https://github.com/jmalicki'
    params = { icon = 'brand-github' }
